java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh01Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh01Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh02Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh02Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh03Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh03Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh04Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh04Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh05Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh05Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh06Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh06Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh07Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh07Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh08Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh08Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh09Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh09Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh10Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh10Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh11Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh11Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh12Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh12Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh13Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh13Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh14Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh14Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh15Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh15Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh16Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh16Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh17Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh17Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh18Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh18Supp.roman -rules:tr.xml -dir:..\data\transcoders -re:SITAroman

java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh01Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh01Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh02Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh02Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh03Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh03Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh04Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh04Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh05Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh05Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh06Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh06Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh07Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh07Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh08Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh08Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh09Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh09Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh10Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh10Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh11Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh11Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh12Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh12Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh13Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh13Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh14Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh14Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh15Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh15Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh16Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh16Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh17Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh17Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
java -jar dist\TranscodeFile.jar -in:C:\Users\ralph\Documents\temp\SuppFinal\MBh18Supp.slp -out:C:\Users\ralph\Documents\temp\SuppFinal\MBh18Supp.deva -rules:tr.xml -dir:..\data\transcoders -re:SITAdeva
